sudo: false
language: node_js

branches:
  only:
    - master

node_js:
  - 4.4.2
  - 4.4.4
  - 'stable'

cache:
  directories:
    - node_modules

matrix:
    allow_failures:
        - node_js: 4.4.2

before_install:
  - gem install sass
  - npm install -g grunt-cli
  - npm install -g grunt
  - npm install -g bower

before_script:
  - npm install
  - bower install

script:
  - grunt travis

after_script:

after_success:
  - coveralls
